// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pdf_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain/models.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  CreatePdfRequest dco_decode_box_autoadd_create_pdf_request(dynamic raw);

  @protected
  CreatePdfRequest dco_decode_create_pdf_request(dynamic raw);

  @protected
  CreatePdfResponse dco_decode_create_pdf_response(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  CreatePdfRequest sse_decode_box_autoadd_create_pdf_request(SseDeserializer deserializer);

  @protected
  CreatePdfRequest sse_decode_create_pdf_request(SseDeserializer deserializer);

  @protected
  CreatePdfResponse sse_decode_create_pdf_response(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_create_pdf_request> cst_encode_box_autoadd_create_pdf_request(
    CreatePdfRequest raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_create_pdf_request();
    cst_api_fill_to_wire_create_pdf_request(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_create_pdf_request(
    CreatePdfRequest apiObj,
    ffi.Pointer<wire_cst_create_pdf_request> wireObj,
  ) {
    cst_api_fill_to_wire_create_pdf_request(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_create_pdf_request(
    CreatePdfRequest apiObj,
    wire_cst_create_pdf_request wireObj,
  ) {
    wireObj.output_path = cst_encode_String(apiObj.outputPath);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.body = cst_encode_String(apiObj.body);
    wireObj.author = cst_encode_opt_String(apiObj.author);
    wireObj.image_bytes = cst_encode_opt_list_prim_u_8_strict(apiObj.imageBytes);
  }

  @protected
  void cst_api_fill_to_wire_create_pdf_response(
    CreatePdfResponse apiObj,
    wire_cst_create_pdf_response wireObj,
  ) {
    wireObj.file_path = cst_encode_String(apiObj.filePath);
    wireObj.file_name = cst_encode_String(apiObj.fileName);
    wireObj.file_size_bytes = cst_encode_u_64(apiObj.fileSizeBytes);
    wireObj.page_count = cst_encode_u_32(apiObj.pageCount);
  }

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_pdf_request(CreatePdfRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_pdf_request(CreatePdfRequest self, SseSerializer serializer);

  @protected
  void sse_encode_create_pdf_response(CreatePdfResponse self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__pdf_api__create_simple_pdf(
    int port_,
    ffi.Pointer<wire_cst_create_pdf_request> request,
  ) {
    return _wire__crate__api__pdf_api__create_simple_pdf(port_, request);
  }

  late final _wire__crate__api__pdf_api__create_simple_pdfPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_create_pdf_request>)>
      >('frbgen_pdf_bridge_app_wire__crate__api__pdf_api__create_simple_pdf');
  late final _wire__crate__api__pdf_api__create_simple_pdf =
      _wire__crate__api__pdf_api__create_simple_pdfPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_create_pdf_request>)>();

  ffi.Pointer<wire_cst_create_pdf_request> cst_new_box_autoadd_create_pdf_request() {
    return _cst_new_box_autoadd_create_pdf_request();
  }

  late final _cst_new_box_autoadd_create_pdf_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_create_pdf_request> Function()>>(
        'frbgen_pdf_bridge_app_cst_new_box_autoadd_create_pdf_request',
      );
  late final _cst_new_box_autoadd_create_pdf_request = _cst_new_box_autoadd_create_pdf_requestPtr
      .asFunction<ffi.Pointer<wire_cst_create_pdf_request> Function()>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(int len) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
        'frbgen_pdf_bridge_app_cst_new_list_prim_u_8_strict',
      );
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>('dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling = _dummy_method_to_enforce_bundlingPtr
      .asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_create_pdf_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> body;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> author;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> image_bytes;
}

final class wire_cst_create_pdf_response extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> file_name;

  @ffi.Uint64()
  external int file_size_bytes;

  @ffi.Uint32()
  external int page_count;
}

const double PAGE_WIDTH_PT = 595.0;

const double PAGE_HEIGHT_PT = 842.0;

const double LEFT_MARGIN_PT = 50.0;

const double TOP_Y_PT = 780.0;

const double TITLE_FONT_SIZE = 22.0;

const double BODY_FONT_SIZE = 12.0;

const double AUTHOR_Y_PT = 750.0;

const double BODY_START_Y_PT = 725.0;

const double LINE_HEIGHT_PT = 18.0;

const double BOTTOM_MARGIN_PT = 40.0;
