// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CreatePdfRequest {
  final String outputPath;
  final String title;
  final String body;
  final String? author;
  final Uint8List? imageBytes;

  const CreatePdfRequest({
    required this.outputPath,
    required this.title,
    required this.body,
    this.author,
    this.imageBytes,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^ title.hashCode ^ body.hashCode ^ author.hashCode ^ imageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreatePdfRequest &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          title == other.title &&
          body == other.body &&
          author == other.author &&
          imageBytes == other.imageBytes;
}

class CreatePdfResponse {
  final String filePath;
  final String fileName;
  final BigInt fileSizeBytes;
  final int pageCount;

  const CreatePdfResponse({
    required this.filePath,
    required this.fileName,
    required this.fileSizeBytes,
    required this.pageCount,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^ fileName.hashCode ^ fileSizeBytes.hashCode ^ pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreatePdfResponse &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          fileName == other.fileName &&
          fileSizeBytes == other.fileSizeBytes &&
          pageCount == other.pageCount;
}
